/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const prefixed = (prefix) => (item) => typeof item === 'string' ? `${prefix}/${item}` : item;

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  /** Forward */
  forward: [
    'readme',
    {
      type: 'category',
      label: 'JavaScript',
      items: [
        'inheritance',
        'eventloop'
      ].map(prefixed('forward/javascript')),
    },
    {
      type: 'category',
      label: 'React',
      items: [
        'lifecycle'
      ].map(prefixed('forward/react')),
    },
    {
      type: 'category',
      label: 'Vue.js',
      items: [
        'readme',
        'data-driven',
        'componentization',
        'reactive',
        'compile',
        'lifecycle',
        'next-tick',
        'computed-vs-watch',
        'component-update',
        'v-model',
        'mvvm',
      ].map(prefixed('forward/vue')),
    },
    {
      type: 'category',
      label: 'Node.js',
      items: 
      ['readme'
    ].map(prefixed('forward/nodejs')),
    },
    {
      type: 'category',
      label: '浏览器',
      items: [
        'from-url-to-page-load',
        'storage',
        'cache',
        'gc',
        'cross-origin',
      ].map(prefixed('forward/browser')),
    },
    {
      type: 'category',
      label: '设计模式',
      items: ['readme'].map(prefixed('forward/design-pattern')),
    },
  ].map(prefixed('forward')),

  /** Engineering */
  engineering: [
    'readme',
    'module',
    {
      type: 'category',
      label: 'Webpack',
      collapsed: false,
      items: [
        'build-process',
        'optimization-analysis',
        'source-map',
        'hot-module-replacement',
        'webpack5',
      ].map(prefixed('engineering/webpack')),
    },
    'tree-shaking',
    'rollup-usage',
    'typescript',
    'web-framework-design',
    'microfrontend',
  ].map(prefixed('engineering')),

  /** Performance */
  performance: [
    'readme',
    {
      type: 'doc',
      id: 'engineering/webpack/optimization-analysis',
    },
    'project-practice',
  ].map(prefixed('performance')),

  /** Practice */
  practice: [
    'readme',
  ].map(prefixed('practice')),

  /** Interview */
  interview: [
    'readme',
    {
      type: 'category',
      label: '数据结构',
      items: [
        'stack',
        'queue',
        'deque',
        'linked-list',
        'doubly-linked-list',
        'binary-search-tree',
        'binary-heap',
      ].map(prefixed('interview/data-structures')),
    },
    {
      type: 'category',
      label: '算法',
      items: [
        'readme',
        'template',
        'dynamic-programing',
        'backtrack',
        'leetcode',
      ].map(prefixed('interview/algorithms')),
    },
    {
      type: 'category',
      label: '排序算法',
      items: [
        'readme',
        'bubble',
        'selection',
        'insertion',
        'merge',
        'quick',
      ].map(prefixed('interview/sorts')),
    },
    {
      type: 'category',
      label: '模拟实现',
      items: [
        'debunce-throttle',
        'clone-deep',
        'call-apply-bind',
        'new',
        'instanceof',
        'promise',
        'localstorage',
        'array-flat',
        'curry',
        'jsonp',
        'merge-promise',
        'concurrent-poll',
      ].map(prefixed('interview/handwrittens')),
    },
    {
      type: 'category',
      label: '面试题目合辑',
      items: [
        'html',
        'css',
        'javascript',
        'vue',
        'webpack',
        'browser',
        'network',
        'performance',
        'others',
      ].map(prefixed('interview/questions')),
    },
  ].map(prefixed('interview')),

  browser: [
    'readme',
    {
      type: 'category',
      label: '宏观视角上的浏览器',
      items: [
        'lesson01',
        'lesson02',
        'lesson03',
        'lesson04',
        'lesson05',
        'lesson06',
      ].map(prefixed('browser-working-principle/part1')),
    },
    {
      type: 'category',
      label: '浏览器中的JavaScript执行机制',
      items: [
        'lesson07',
        'lesson08',
        'lesson09',
        'lesson10',
        'lesson11',
      ].map(prefixed('browser-working-principle/part2')),
    },
    {
      type: 'category',
      label: 'V8工作原理',
      items: [
        'lesson12',
        'lesson13',
        'lesson14',
      ].map(prefixed('browser-working-principle/part3')),
    },
    {
      type: 'category',
      label: '浏览器中的页面循环系统',
      items: [
        'lesson15',
        'lesson16',
        'lesson17',
        'lesson18',
        'lesson19',
        'lesson20',
      ].map(prefixed('browser-working-principle/part4')),
    },
    {
      type: 'category',
      label: '浏览器中的页面',
      items: [
        'lesson21',
        'lesson22',
        'lesson23',
        'lesson24',
        'lesson25',
        'lesson26',
        'lesson27',
        'lesson28',
      ].map(prefixed('browser-working-principle/part5')),
    },
    {
      type: 'category',
      label: '浏览器中的网络',
      items: [
        'lesson29',
        'lesson30',
        'lesson31',
        'lesson32',
        'lesson33',
        'lesson34',
        'lesson35',
        'lesson36',
      ].map(prefixed('browser-working-principle/part6')),
    },
  ].map(prefixed('browser-working-principle')),
};
